### ISSUE TITLE
Yellow Paper restructure proposal

### ISSUE THREAD

**Issue by akegaviar** [UOSnetwork/uos.docs#1]
The yellow paper at https://github.com/UOSnetwork/uos.docs/tree/master/yellow_paper needs restructuring and must be updated with the latest information.

This issue specifically addresses a new structure proposal.

**Comment by ghost** [comment]
Offer this struvture:

Contents
1 Introduction
  1.1 Previouswork
  1.2 Motivation
2 U◦ OS consensus algorithm 
  2.1 Importancescorecalculation
    2.1.1 Financial activity score calculation 
    2.1.2 Socialactivityscorecalculation 
 2.2 Importancescoreusage
 2.3 Keyfeaturesofthealgorithm 
3 Emission 
  3.1 U◦OS token utilization 
  3.2 Calculating network activity for a period of time 
  3.3 Emissionvaluecalculation 
4 U◦ OS framework architecture 
Appendix 1 Glossary of terms 
References

**Comment by akegaviar** [comment]
Looks good!
