### ISSUE TITLE
Error in yellow paper

### ISSUE THREAD

**Issue by iamredbar** [UOSnetwork/uos.docs#16]
Error in yellow paper
-----

There are the words "insert hyperlink here" instead of a hyperlink.

Summary
-------

On page 17 in the footer, a placeholder is there instead of the correct link.

Environment
-----------

Github

Steps to reproduce
------------------

* Navigate to the yellow paper (https://github.com/UOSnetwork/uos.docs/blob/master/yellow_paper/uos_yellow_paper.eng.pdf)
* View footer on page 17

Expected result
---------------

A link instead of a place holder

Current result
--------------

Placeholder text

**Comment by akegaviar** [comment]
Thanks for the report! @NataliaRodchenko pls have a look.

**Comment by iamredbar** [comment]
Anytime @akegaviar!

**Comment by ghost** [comment]
fixed now
