### ISSUE TITLE
Discrepancy in account name conventions

### ISSUE THREAD

**Issue by 0x-Cobra** [UOSnetwork/uos.docs#18]
Discrepancy in account name conventions
-----

Summary
-------

In [Spinning up a Block Producer Node on Ubuntu](https://github.com/UOSnetwork/uos.docs/blob/master/uosBPubuntu.md#8-contact-the-uos-developers) documentation, in the chapter 8, is written that account name **must** start with a letter.
But the example indicates `123example345` that starts with a number. 

Environment
-----------

NA

Steps to reproduce
------------------

NA

Expected result
---------------

Correct documentation.

Current result
--------------

NA

Possible Fix
------------

"Must start with a letter" seems not accurate as `123example345` passes validation on u.community registration page.

Additional information
----------------------

NA

Examples
--------

NA

**Comment by ghost** [comment]
fixed
