### ISSUE TITLE
[YellowPaper] Add Abstract, Introduction, Motivation, Previous work, Algo description, Plan architecture section

### ISSUE THREAD

**Issue by akegaviar** [UOSnetwork/uos.docs#2]
As part of our ongoing efforts to bring the Yellow Paper up to date and make it digestible, we need to expand on and add the following sections:

– Abstract
– Introduction
– Motivation
– Previous work
– Algo description
– Plan architecture section

**Comment by akegaviar** [comment]
We'll keep it in TEX as it's the easiest format to work with formulas.

**Comment by akegaviar** [comment]
@NataliaRodchenko any update on this?

**Comment by ghost** [comment]
Yes, I can commit a new version

**Comment by ghost** [comment]
Commited to the branch yellow.paper - commit id: d5e798d

**Comment by akegaviar** [comment]
There are comments in the commit in the pdf file. I can't merge this to master.
 Can you pls commit a version with no comments in red?

![image](https://user-images.githubusercontent.com/10195782/52338702-30577680-2a1c-11e9-8b03-a5776565d1e4.png)

**Comment by akegaviar** [comment]
Any update on this?
